language: ruby
rvm:
  - 2.1.3
services:
  - postgresql
  - redis-server
  - memcached
env:
  - RAILS_ENV=test
bundler_args: --jobs=3 --retry=3 --deployment --without development production
before_install:
  - bundle config build.nokogiri --use-system-libraries
before_script:
  - bundle exec rake db:create db:structure:load
script:
  - bundle exec rspec spec
addons:
  postgresql: "9.3"
notifications:
  webhooks:
    urls:
      - https://app.opslevel.com/integrations/deploy/2d9d6f76-107c-4861-8387-38ec24a5fc7a
    on_success: change # default: always
    on_failure: always # default: always
    on_start:   change # default: never
    on_cancel:  always # default: always
    on_error:   always # default: always
    template: 
        - "%{repository_slug} (%{commit}) : %{message}"
        - "Build details: %{build_url}"
